apiVersion: v1
kind: Pod
metadata:
  name: ckad-ubuntu-qwfefefwe
  namespace: ckad-pod-design
spec:
  containers:
  - name: ubuntu-server
    image: ubuntu
    command: ["/bin/sh", "-c", "sleep 3600"]