apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"simple-webapp-aom"},"name":"simple-webapp-aom","namespace":"default"},"spec":{"containers":[{"image":"kodekloud/webapp-delayed-start","name":"simple-webapp","ports":[{"containerPort":8080}]}]}}
  creationTimestamp: "2026-03-30T17:34:14Z"
  generation: 1
  labels:
    name: simple-webapp-aom
  name: simple-webapp-aom
  namespace: default
  resourceVersion: "5930"
  uid: 43e67375-85ef-4292-aa32-99d2d375f5c4
spec:
  containers:
  - image: kodekloud/webapp-delayed-start
    imagePullPolicy: Always
    name: simple-webapp
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vlxqd
      readOnly: true
    readinessProbe:
      initialDelaySeconds: 15
      httpGet:
        path: /ready
        port: 8080
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cluster1-node01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vlxqd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-03-30T17:34:18Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-03-30T17:34:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-03-30T17:34:18Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-03-30T17:34:18Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-03-30T17:34:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://bb0701d157501148757a6afc13d50d919afba6fbb73733c81bcf575bca288f63
    image: docker.io/kodekloud/webapp-delayed-start:latest
    imageID: docker.io/kodekloud/webapp-delayed-start@sha256:666b95c2ef8e00a74fa0ea96def8d9d69104ec5d9b9b0f49d8a76bd4c94ad343
    lastState: {}
    name: simple-webapp
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-30T17:34:17Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vlxqd
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.244.198.243
  hostIPs:
  - ip: 10.244.198.243
  phase: Running
  podIP: 10.42.1.5
  podIPs:
  - ip: 10.42.1.5
  qosClass: BestEffort
  startTime: "2026-03-30T17:34:14Z"