apiVersion: v1
kind: Pod
metadata:
  name: webapp-svcn
  labels:
    tier: msg
spec:
  containers:
  - name: webapp-svcn
    image: kodekloud/webapp-color
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service-svcn
spec:
  selector:
    tier: msg
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 8080