apiVersion: v1
kind: Pod
metadata:
  name: ckad-neighbor-pod
  namespace: ckad-multi-containers
spec:
  containers:
  - name: main-container
    image: nginx:1.16
    volumeMounts:
    - name: my-vol
      mountPath: /usr/share/nginx/html
  - name: neighbor-container
    image: busybox:1.28
    volumeMounts:
    - name: my-vol
      mountPath: /var/log
    command:
    - /bin/sh
    - -c
    args:
    - while true; do echo "Hello from neighbor container" >> /var/log/index.html; sleep 5; done
  volumes:
  - name: my-vol
    emptyDir: {}